version: '3.9'

networks:
  app_net:

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    environment:
      NETLIFY_TOKEN: ${NETLIFY_TOKEN}
    networks:
      - app_net

  application:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - app_net
    environment:
      - NODE_ENV=production
    ports: [3000]
    labels:
      - "traefik.http.routers.${NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=myresolver"
